[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.26"

[features]
resolution = true
skip-lint = false

[programs.devnet]
savefi = "6ttMWaSxYvukX3dYJwuGCp7eaHWL6Fw28ZRhsULWMPp9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
