[workspace]
members = [
  "programs/savefi"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.release]
overflow-checks = true

[workspace.dependencies]
proc-macro2 = "1.0.56"


